# Generated by Django 5.2.8 on 2025-11-22 06:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nida_card',
            field=models.ImageField(blank=True, null=True, upload_to='nida_cards/'),
        ),
        migrations.AddField(
            model_name='user',
            name='nida_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid NIDA number (20 digits).', regex='^[0-9]{20}$')]),
        ),
        migrations.AddField(
            model_name='user',
            name='user_verified',
            field=models.BooleanField(default=False),
        ),
    ]
