# Generated by Django 5.2.8 on 2025-11-22 07:27

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_nida_card_user_nida_number_user_user_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nida_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[account.models.validate_nida]),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('property_owner', 'Property Owner')], default='customer', max_length=30),
        ),
    ]
