# Generated by Django 5.2.8 on 2026-02-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_account", "0004_alter_otptoken_otp_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otptoken",
            name="otp_code",
            field=models.CharField(default="55b487", max_length=6),
        ),
    ]
