# Generated by Django 5.2.8 on 2026-02-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_account", "0007_alter_otptoken_otp_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otptoken",
            name="otp_code",
            field=models.CharField(default="7fd011", max_length=6),
        ),
    ]
