# Generated by Django 5.2.8 on 2026-02-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_account", "0009_alter_otptoken_otp_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otptoken",
            name="otp_code",
            field=models.CharField(default="a4dcc0", max_length=6),
        ),
    ]
