# Generated by Django 5.2.8 on 2026-02-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_account", "0010_alter_otptoken_otp_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otptoken",
            name="otp_code",
            field=models.CharField(default="f7b63b", max_length=6),
        ),
    ]
