# Generated by Django 5.2.8 on 2026-03-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_account", "0011_alter_otptoken_otp_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otptoken",
            name="otp_code",
            field=models.CharField(default="7fbd58", max_length=6),
        ),
    ]
