# Generated by Django 6.0.5 on 2026-05-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_account', '0022_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='2a47b7', max_length=6),
        ),
    ]
