# Generated by Django 5.2.8 on 2025-11-25 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=255)),
                ('car_type', models.CharField(choices=[('shuffle', 'Shuffles'), ('moving_logistic', 'Moving Logistic'), ('piki_piki_bajaji', 'Piki Piki/Bajaji')], max_length=50)),
                ('car_description', models.TextField(blank=True, null=True)),
                ('registration_number', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('model_year', models.PositiveIntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('seats', models.PositiveIntegerField(default=1)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('has_air_conditioning', models.BooleanField(default=False)),
                ('automatic_transmission', models.BooleanField(default=False)),
                ('fuel_type', models.CharField(blank=True, max_length=50, null=True)),
                ('mileage_km', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarRentalLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_and_conditions', models.TextField(blank=True, null=True)),
                ('rental_policy', models.TextField(blank=True, null=True)),
                ('cancellation_policy', models.TextField(blank=True, null=True)),
                ('deposit_policy', models.TextField(blank=True, null=True)),
                ('insurance_details', models.TextField(blank=True, null=True)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carrental.carrental')),
            ],
        ),
        migrations.CreateModel(
            name='CarRentalPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_rental_photos/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='carrental.carrental')),
            ],
        ),
        migrations.CreateModel(
            name='CarRentalPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price_per_day', models.DecimalField(decimal_places=2, max_digits=12)),
                ('weekly_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('monthly_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cleaning_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tax_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('currency', models.CharField(default='TZS', max_length=10)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carrental.carrental')),
            ],
        ),
        migrations.CreateModel(
            name='CarRentalSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_gps', models.BooleanField(default=False)),
                ('has_radio', models.BooleanField(default=False)),
                ('has_music_system', models.BooleanField(default=False)),
                ('safety_features', models.JSONField(blank=True, default=list)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carrental.carrental')),
            ],
        ),
    ]
