# Generated by Django 5.2.8 on 2026-02-09 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resedence", "0002_alter_residenceproperty_property_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="residencepropertypricing",
            name="max_months",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="residencepropertypricing",
            name="min_months",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="residenceproperty",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("apartment", "Apartment"),
                    ("house", "House"),
                    ("office_space", "Office Space"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="OfficePropertySetup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "building_condition",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("old", "Old"),
                            ("very_old", "Very Old"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "floor_finish",
                    models.CharField(
                        choices=[("tiles", "Tiles"), ("normal_floor", "Normal Floor")],
                        max_length=20,
                    ),
                ),
                (
                    "door_type",
                    models.CharField(
                        choices=[
                            ("glass_grill", "Glass & Grill"),
                            ("iron_grill", "Iron Sheet & Grill"),
                            ("grill_only", "Grill Only"),
                        ],
                        max_length=20,
                    ),
                ),
                ("office_size_sqm", models.PositiveIntegerField()),
                ("number_of_tenants", models.PositiveIntegerField(default=1)),
                (
                    "toilet_type",
                    models.CharField(
                        choices=[("squat", "Squat Toilet"), ("sit", "Sitting Toilet")],
                        max_length=20,
                    ),
                ),
                (
                    "building_level",
                    models.CharField(
                        choices=[
                            ("ground_floor", "Ground Floor"),
                            ("storey_building", "Storey Building"),
                        ],
                        max_length=20,
                    ),
                ),
                ("floor_number", models.PositiveIntegerField(blank=True, null=True)),
                ("has_water", models.BooleanField(default=True)),
                ("has_electricity", models.BooleanField(default=True)),
                (
                    "electricity_usage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("private", "Private (Only You)"),
                            ("shared", "Shared"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "fan_or_ac",
                    models.CharField(
                        choices=[
                            ("fan", "Fan"),
                            ("ac", "Air Conditioner"),
                            ("none", "None"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "ceiling_type",
                    models.CharField(
                        choices=[
                            ("ceiling_board", "Ceiling Board"),
                            ("gypsum", "Gypsum"),
                            ("none", "None"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("has_security_guard", models.BooleanField(default=False)),
                (
                    "window_type",
                    models.CharField(
                        choices=[
                            ("glass", "Glass Windows"),
                            ("wire_mesh", "Wire Mesh Windows"),
                            ("none", "No Windows"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "door_lock_condition",
                    models.CharField(
                        choices=[("good", "Good"), ("needs_repair", "Needs Repair")],
                        max_length=20,
                    ),
                ),
                (
                    "road_type",
                    models.CharField(
                        choices=[
                            ("main_road", "Main Road"),
                            ("street_road", "Street Road"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("quiet", "Quiet"),
                            ("moderate_noise", "Moderate Noise"),
                            ("normal", "Normal"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "location_category",
                    models.CharField(
                        choices=[
                            ("city_center", "City Center"),
                            ("residential_area", "Residential/Uswahilini"),
                            ("normal", "Normal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("number_of_offices", models.PositiveIntegerField(default=1)),
                (
                    "property",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="office_setup",
                        to="resedence.residenceproperty",
                    ),
                ),
            ],
        ),
    ]
