# Generated by Django 5.2.8 on 2026-02-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resedence", "0003_residencepropertypricing_max_months_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="officepropertysetup",
            name="electricity_usage",
        ),
        migrations.RemoveField(
            model_name="officepropertysetup",
            name="toilet_type",
        ),
        migrations.AddField(
            model_name="officepropertysetup",
            name="toilet_available",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default=False, max_length=20
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="residenceproperty",
            name="electricity_type",
            field=models.CharField(
                blank=True,
                choices=[("private", "Private (Only You)"), ("shared", "Shared")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="residenceproperty",
            name="water_supply",
            field=models.CharField(
                blank=True,
                choices=[("private", "Private (Only You)"), ("shared", "Shared")],
                max_length=20,
                null=True,
            ),
        ),
    ]
