# Generated by Django 5.2.8 on 2026-02-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resedence", "0004_remove_officepropertysetup_electricity_usage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="residenceproperty",
            name="airbnb_available",
            field=models.CharField(
                blank=True,
                choices=[("yes", "Yes"), ("no", "No")],
                max_length=3,
                null=True,
            ),
        ),
    ]
