# Generated by Django 5.2.8 on 2026-02-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resedence", "0005_residenceproperty_airbnb_available"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="residencepropertypricing",
            name="monthly_discount",
        ),
        migrations.RemoveField(
            model_name="residencepropertypricing",
            name="tax_percentage",
        ),
        migrations.RemoveField(
            model_name="residencepropertypricing",
            name="weekly_discount",
        ),
        migrations.AddField(
            model_name="residencepropertypricing",
            name="rent_duration",
            field=models.IntegerField(
                choices=[(3, "3 Months"), (6, "6 Months"), (12, "12 Months")],
                default=False,
            ),
            preserve_default=False,
        ),
    ]
