# Generated by Django 5.2.8 on 2026-02-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resedence", "0007_remove_officepropertysetup_building_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="residenceproperty",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("apartment", "Apartment"),
                    ("homes", "Homes"),
                    ("office_space", "Office Space"),
                ],
                max_length=20,
            ),
        ),
    ]
