# Generated by Django 5.2.8 on 2025-11-23 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=255)),
                ('property_type', models.CharField(choices=[('hotel', 'Hotel'), ('lodge', 'Lodge'), ('guest_house', 'Guest House'), ('tent or campsite', 'Tent or campsite')], max_length=20)),
                ('property_description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=50)),
                ('country', models.CharField(default='Tanzania', max_length=50)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('property_size_sqm', models.PositiveIntegerField(blank=True, null=True)),
                ('languages_spoken', models.JSONField(blank=True, default='Kiswahili')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookingPropertyLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_and_conditions', models.TextField(blank=True, null=True)),
                ('house_rules', models.TextField(blank=True, null=True)),
                ('cancellation_policy', models.TextField(blank=True, null=True)),
                ('check_in_policy', models.TextField(blank=True, null=True)),
                ('smoking_policy', models.TextField(blank=True, null=True)),
                ('pet_policy', models.TextField(blank=True, null=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.bookingproperty')),
            ],
        ),
        migrations.CreateModel(
            name='BookingPropertyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='booking_property_photos/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='booking.bookingproperty')),
            ],
        ),
        migrations.CreateModel(
            name='BookingPropertyPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_from', models.DateField()),
                ('available_to', models.DateField()),
                ('minimum_stay_nights', models.PositiveIntegerField(default=1)),
                ('maximum_stay_nights', models.PositiveIntegerField(blank=True, null=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.bookingproperty')),
            ],
        ),
        migrations.CreateModel(
            name='BookingPropertySetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_rooms', models.IntegerField(default=1)),
                ('beds_per_room', models.IntegerField(default=1)),
                ('max_guests_per_room', models.IntegerField(default=1)),
                ('total_beds', models.IntegerField(blank=True, null=True)),
                ('number_of_bathrooms', models.IntegerField(default=1)),
                ('has_kitchen', models.BooleanField(default=False)),
                ('has_living_room', models.BooleanField(default=False)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('room_types', models.JSONField(blank=True, default=list)),
                ('accessibility_features', models.JSONField(blank=True, default=list)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.bookingproperty')),
            ],
        ),
    ]
