# Generated by Django 5.2.8 on 2025-11-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingproperty',
            options={'verbose_name': 'BookingProperty', 'verbose_name_plural': 'Booking Properties'},
        ),
        migrations.AlterField(
            model_name='bookingproperty',
            name='languages_spoken',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
