# Generated by Django 5.2.8 on 2026-02-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0004_alter_bookingproperty_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingproperty",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("hotel", "Hotel"),
                    ("lodge", "Lodge"),
                    ("guest_house", "Guest House"),
                    ("tent or campsite", "Tent or campsite"),
                    ("villa", "Villas"),
                    ("resort", "Resort"),
                ],
                max_length=20,
            ),
        ),
    ]
