# Generated by Django 4.2.29 on 2026-07-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_booking_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingproperty',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('hold', 'Hold')], default='open', max_length=10),
        ),
    ]
