# Generated by Django 4.2.29 on 2026-08-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_bookingproperty_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpropertylegal',
            name='deposit_policy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingpropertysetup',
            name='building_level',
            field=models.CharField(blank=True, choices=[('Ground Building', 'Ground Building'), ('Multi-Storey Building', 'Multi-Storey Building')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookingpropertysetup',
            name='cctv_camera',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingpropertysetup',
            name='fenced_compound',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingpropertysetup',
            name='has_fridge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingpropertysetup',
            name='security_guard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingpropertysetup',
            name='year_built',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
