# Generated by Django 4.2.29 on 2026-08-13 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_bookingpropertylegal_deposit_policy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingpropertysetup',
            name='has_fridge',
        ),
    ]
