# Generated by Django 4.2.29 on 2026-08-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_remove_bookingpropertysetup_has_fridge'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingproperty',
            name='current_step',
            field=models.CharField(choices=[('property', 'Property Information'), ('setup', 'Property Setup'), ('pricing', 'Pricing'), ('legal', 'Legal Information'), ('photos', 'Photos'), ('complete', 'Complete')], default='property', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookingproperty',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bookingproperty',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookingproperty',
            name='property_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bookingproperty',
            name='property_type',
            field=models.CharField(blank=True, choices=[('hotel', 'Hotel'), ('lodge', 'Lodge'), ('guest_house', 'Guest House'), ('tent or campsite', 'Tent or campsite'), ('villa', 'Villas'), ('resort', 'Resort')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bookingproperty',
            name='region',
            field=models.CharField(blank=True, choices=[('Arusha', 'Arusha'), ('Dar es Salaam', 'Dar es Salaam'), ('Dodoma', 'Dodoma'), ('Geita', 'Geita'), ('Iringa', 'Iringa'), ('Kagera', 'Kagera'), ('Katavi', 'Katavi'), ('Kigoma', 'Kigoma'), ('Kilimanjaro', 'Kilimanjaro'), ('Lindi', 'Lindi'), ('Manyara', 'Manyara'), ('Mara', 'Mara'), ('Mbeya', 'Mbeya'), ('Morogoro', 'Morogoro'), ('Mtwara', 'Mtwara'), ('Mwanza', 'Mwanza'), ('Njombe', 'Njombe'), ('Pwani', 'Pwani (Coast)'), ('Rukwa', 'Rukwa'), ('Ruvuma', 'Ruvuma'), ('Shinyanga', 'Shinyanga'), ('Simiyu', 'Simiyu'), ('Singida', 'Singida'), ('Songwe', 'Songwe'), ('Tabora', 'Tabora'), ('Tanga', 'Tanga'), ('Zanzibar North', 'Zanzibar North'), ('Zanzibar South', 'Zanzibar South'), ('Zanzibar Central/South', 'Zanzibar Central/South'), ('Zanzibar Urban/West', 'Zanzibar Urban/West')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bookingpropertypricing',
            name='available_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingpropertypricing',
            name='available_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingpropertypricing',
            name='base_price_per_night',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
