# Generated by Django 4.2.29 on 2026-08-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_bookingproperty_current_step_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingproperty',
            name='current_step',
            field=models.CharField(choices=[('property', 'Property Information'), ('setup', 'Property Setup'), ('photos', 'Photos'), ('pricing', 'Pricing'), ('legal', 'Legal Information'), ('complete', 'Complete')], default='property', max_length=20),
        ),
    ]
