# Generated by Django 6.0.1 on 2026-01-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingproperty',
            name='region',
            field=models.CharField(choices=[('Arusha', 'Arusha'), ('Dar es Salaam', 'Dar es Salaam'), ('Dodoma', 'Dodoma'), ('Geita', 'Geita'), ('Iringa', 'Iringa'), ('Kagera', 'Kagera'), ('Katavi', 'Katavi'), ('Kigoma', 'Kigoma'), ('Kilimanjaro', 'Kilimanjaro'), ('Lindi', 'Lindi'), ('Manyara', 'Manyara'), ('Mara', 'Mara'), ('Mbeya', 'Mbeya'), ('Morogoro', 'Morogoro'), ('Mtwara', 'Mtwara'), ('Mwanza', 'Mwanza'), ('Njombe', 'Njombe'), ('Pwani', 'Pwani (Coast)'), ('Rukwa', 'Rukwa'), ('Ruvuma', 'Ruvuma'), ('Shinyanga', 'Shinyanga'), ('Simiyu', 'Simiyu'), ('Singida', 'Singida'), ('Songwe', 'Songwe'), ('Tabora', 'Tabora'), ('Tanga', 'Tanga'), ('Zanzibar North', 'Zanzibar North'), ('Zanzibar South', 'Zanzibar South'), ('Zanzibar Central/South', 'Zanzibar Central/South'), ('Zanzibar Urban/West', 'Zanzibar Urban/West')], max_length=50),
        ),
    ]
