# Generated by Django 5.2.8 on 2026-03-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0005_alter_bookingproperty_property_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="phone_number",
            field=models.CharField(default=False, max_length=20),
            preserve_default=False,
        ),
    ]
