# Generated by Django 5.2.8 on 2025-11-24 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidenceProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=255)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('frame', 'Frame')], max_length=20)),
                ('property_description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=50)),
                ('country', models.CharField(default='Tanzania', max_length=50)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('property_size_sqm', models.PositiveIntegerField(blank=True, null=True)),
                ('year_built', models.PositiveIntegerField(blank=True, null=True)),
                ('floors', models.PositiveIntegerField(blank=True, null=True)),
                ('furnished', models.BooleanField(default=False)),
                ('parking_available', models.BooleanField(default=False)),
                ('parking_spaces', models.PositiveIntegerField(blank=True, null=True)),
                ('electricity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('water_supply', models.CharField(blank=True, max_length=50, null=True)),
                ('internet_available', models.BooleanField(default=False)),
                ('has_cctv', models.BooleanField(default=False)),
                ('has_security_guard', models.BooleanField(default=False)),
                ('fenced_compound', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('hold', 'Hold'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResidencePropertyLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_and_conditions', models.TextField(blank=True, null=True)),
                ('house_rules', models.TextField(blank=True, null=True)),
                ('cancellation_policy', models.TextField(blank=True, null=True)),
                ('deposit_policy', models.TextField(blank=True, null=True)),
                ('refund_rules', models.TextField(blank=True, null=True)),
                ('insurance_details', models.TextField(blank=True, null=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resedence.residenceproperty')),
            ],
        ),
        migrations.CreateModel(
            name='ResidencePropertyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='residence_property_photos/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='resedence.residenceproperty')),
            ],
        ),
        migrations.CreateModel(
            name='ResidencePropertyPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('weekly_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('monthly_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cleaning_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tax_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('currency', models.CharField(default='TZS', max_length=10)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resedence.residenceproperty')),
            ],
        ),
        migrations.CreateModel(
            name='ResidencePropertySetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_rooms', models.IntegerField(default=1)),
                ('beds_per_room', models.IntegerField(default=1)),
                ('max_guests_per_room', models.IntegerField(default=1)),
                ('total_beds', models.IntegerField(blank=True, null=True)),
                ('number_of_bathrooms', models.IntegerField(default=1)),
                ('bathroom_types', models.JSONField(blank=True, default=list)),
                ('has_kitchen', models.BooleanField(default=False)),
                ('kitchen_type', models.CharField(blank=True, choices=[('private', 'Private Kitchen'), ('shared', 'Shared Kitchen'), ('none', 'No Kitchen')], max_length=50, null=True)),
                ('has_living_room', models.BooleanField(default=False)),
                ('living_room_size_sqm', models.PositiveIntegerField(blank=True, null=True)),
                ('room_types', models.JSONField(blank=True, default=list)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('accessibility_features', models.JSONField(blank=True, default=list)),
                ('has_balcony', models.BooleanField(default=False)),
                ('has_storage_room', models.BooleanField(default=False)),
                ('has_laundry_room', models.BooleanField(default=False)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resedence.residenceproperty')),
            ],
        ),
    ]
