# Generated by Django 5.2.8 on 2026-02-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resedence", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="residenceproperty",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("apartment", "Apartment"),
                    ("house", "House"),
                    ("office space", "Office Space"),
                ],
                max_length=20,
            ),
        ),
    ]
