# Generated by Django 5.2.8 on 2026-02-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resedence", "0006_remove_residencepropertypricing_monthly_discount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="officepropertysetup",
            name="building_level",
        ),
        migrations.RemoveField(
            model_name="officepropertysetup",
            name="has_security_guard",
        ),
        migrations.AddField(
            model_name="residenceproperty",
            name="building_level",
            field=models.CharField(
                choices=[
                    ("ground_floor", "Ground Floor"),
                    ("storey_building", "Storey Building"),
                ],
                default=False,
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
