# Generated by Django 5.2.8 on 2026-02-16 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resedence", "0008_alter_residenceproperty_property_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="officepropertysetup",
            name="floor_number",
        ),
    ]
