# Generated by Django 6.0.5 on 2026-05-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resedence', '0011_residencebooking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='residenceproperty',
            old_name='airbnb_available',
            new_name='bnb_available',
        ),
        migrations.AddField(
            model_name='residencepropertypricing',
            name='base_price_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='residencepropertypricing',
            name='monthly_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='residencepropertypricing',
            name='weekly_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
