# Generated by Django 6.0.5 on 2026-05-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resedence', '0012_rename_airbnb_available_residenceproperty_bnb_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residencepropertypricing',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
