# Generated by Django 6.0.5 on 2026-05-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resedence', '0013_alter_residencepropertypricing_base_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residencepropertypricing',
            name='rent_duration',
            field=models.IntegerField(blank=True, choices=[(3, '3 Months'), (6, '6 Months'), (12, '12 Months')], null=True),
        ),
    ]
