# Generated by Django 6.0.5 on 2026-06-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resedence', '0014_alter_residencepropertypricing_rent_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='residencebooking',
            name='check_in_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
