# Generated by Django 6.0.5 on 2026-06-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resedence', '0015_residencebooking_check_in_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residencebooking',
            name='check_in_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
