# Generated by Django 6.0.5 on 2026-06-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resedence', '0016_alter_residencebooking_check_in_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='residencebooking',
            name='check_out_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
