# Generated by Django 6.0.5 on 2026-06-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resedence', '0017_residencebooking_check_out_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residencebooking',
            name='rent_duration',
            field=models.IntegerField(blank=True, choices=[(3, '3 Months'), (6, '6 Months'), (12, '12 Months')], null=True),
        ),
    ]
