# Generated by Django 4.2.29 on 2026-06-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resedence', '0018_alter_residencebooking_rent_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='residencebooking',
            name='adults',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='residencebooking',
            name='children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='residencebooking',
            name='has_parcel',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AddField(
            model_name='residencebooking',
            name='need_bnb',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AddField(
            model_name='residencebooking',
            name='parcel_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
