# Generated by Django 4.2.29 on 2026-08-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resedence', '0019_residencebooking_adults_residencebooking_children_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='residenceproperty',
            name='current_step',
            field=models.CharField(choices=[('property', 'Basic Information'), ('setup', 'Property Setup'), ('photos', 'Photos'), ('pricing', 'Pricing'), ('legal', 'Legal Information'), ('complete', 'Complete')], default='property', max_length=20),
        ),
    ]
