# Generated by Django 4.2.29 on 2026-08-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resedence', '0020_residenceproperty_current_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officepropertysetup',
            name='office_size_sqm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
