# Generated by Django 5.2.8 on 2026-02-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carrental", "0003_carrental_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="carrental",
            name="address",
            field=models.CharField(default=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="carrental",
            name="district",
            field=models.CharField(default=False, max_length=255),
            preserve_default=False,
        ),
    ]
