# Generated by Django 4.2.29 on 2026-04-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrental', '0004_carrental_address_carrental_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbooking',
            name='booking_type',
            field=models.CharField(choices=[('day', 'Per Day'), ('trip', 'Per Trip')], default='day', max_length=10),
        ),
        migrations.AddField(
            model_name='carrentalpricing',
            name='max_price_per_day',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=12),
            preserve_default=False,
        ),
    ]
