# Generated by Django 4.2.29 on 2026-04-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrental', '0005_carbooking_booking_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbooking',
            name='dropoff_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='total_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
